### PR TITLE
skipped sample tests and added github action workflow

### PR DESCRIPTION
**Pull request by Yzm1234**

### CODE REVIEW

**Review by Tianhao-Gu — COMMENTED** [review]
I am not acknowledged why samples are broken. Can you mock some behavior of samples?

**Comment by dcchivian** [comment]
@sychan @scanon @slebras please remind us why we decided it was OK to skip sample unit tests.  If it's not ok to skip them, who can help @Yzm1234 get them fixed?

**Comment by Yzm1234** [comment]
@Tianhao-Gu this is the test results:
[error.txt](https://github.com/kbaseapps/SetAPI/files/5954335/error.txt)
@dcchivian could you explain why sample search broken? I am not very sure what happened

**Comment by dcchivian** [comment]
> @Tianhao-Gu this is the test results:
> [error.txt](https://github.com/kbaseapps/SetAPI/files/5954335/error.txt)
> @dcchivian could you explain why sample search broken? I am not very sure what happened

@Yzm1234 I don't know.  Need @slebras or someone else who knows it better to comment.  IIRC @scanon or @sychan said it was still in dev so we didn't need to require that those tests pass.  But @Tianhao-Gu is of a different opinion.  I would like the tests to pass if at all possible.

**Comment by dcchivian** [comment]
@Tianhao-Gu are you able to get the unit tests with Sample to work?  if so, can you work with @Yzm1234 to figure out what the difference is between your code/data?

**Comment by Tianhao-Gu** [comment]
> @Tianhao-Gu are you able to get the unit tests with Sample to work? if so, can you work with @Yzm1234 to figure out what the difference is between your code/data?

No I wasn’t familiar with sample search. All I am saying is I don’t like the idea of skipping some failing tests so that the whole test suite can pass. If sample search no longer works, new tests should be added.

**Comment by dcchivian** [comment]
@Tianhao-Gu I 100% agree.  I think the reason we skipped the sample-related unit tests was because we thought they were added but never worked at any point, so not only was the Samples stuff in development, the unit tests were too.  But if we were wrong and someone did have them working at one point, we absolutely should get them working again!  Let me see if I can tell who added them.  Hold on... (@sychan @scanon @Yzm1234 please holler if you remember things differently, or have another opinion)

**Comment by dcchivian** [comment]
4 unit tests under consideration are in
https://github.com/kbaseapps/SetAPI/blob/master/test/SampleSetSearch_test.py
  test_sample_set_to_sample_info()
  test_query_search()
  test_prefix_query_search()
  test_prefix_query_search_2()

looks like these tests are from @slebras , so we need him to fill us in on the history and if they were once working.

**Comment by dcchivian** [comment]
ping @slebras @Tianhao-Gu @sychan @scanon @Yzm1234 (see above)

**Comment by Yzm1234** [comment]
see #44

**Pull request closed without merging**
